---
resources:
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/buildpacks-ci.git
    private_key: {{github-private-key}}
- name: ruby-buildpack
  type: git
  source:
    uri: git@github.com:SUSE/cf-ruby-buildpack.git
    private_key: {{github-private-key}}
    branch: aduffeck_obs_build
jobs:
- name: brats
  plan:
  - get: ruby-buildpack
    trigger: true
  - get: ci
    trigger: true
  - task: cleanup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: ci
      params:
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
      run:
        path: ci/tasks/cleanup.sh
  - task: brats
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: ruby-buildpack
        - name: ci
      params:
        GINKGO_NODES: 1
        PROXY_SCHEME: {{brats-proxy-scheme}}
        PROXY_PORT: {{brats-proxy-port}}
        PROXY_USERNAME: {{brats-proxy-username}}
        PROXY_PASSWORD: {{brats-proxy-password}}
        PROXY_HOST: {{brats-proxy-host}}
        CF_STACK: {{brats-cf-stack}}
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
      run:
        path: ci/tasks/brats.sh
