---
resource_types:
- name: lftp-resource
  type: docker-image
  source:
    repository: machinerytool/concourse-lftp-resource
    tag: latest

resources:
- name: lftp.obs-buildpacks-staging
  type: lftp-resource
  source:
    url: https://download.opensuse.org/repositories/Cloud:/Platform:/buildpacks/buildpacks/src/
    regexp: ruby-buildpack-(.*).src.rpm
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/buildpacks-ci.git
    private_key: {{github-private-key}}
jobs:
- name: brats
  plan:
  - get: lftp.obs-buildpacks-staging
    trigger: true
  - get: ci
    trigger: true
  - task: cleanup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: ci
      params:
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
      run:
        path: ci/tasks/cleanup.sh
  - task: brats
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: lftp.obs-buildpacks-staging
        - name: ci
      params:
        GINKGO_NODES: 1
        PROXY_SCHEME: {{brats-proxy-scheme}}
        PROXY_PORT: {{brats-proxy-port}}
        PROXY_USERNAME: {{brats-proxy-username}}
        PROXY_PASSWORD: {{brats-proxy-password}}
        PROXY_HOST: {{brats-proxy-host}}
        CF_STACK: {{brats-cf-stack}}
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
      run:
        path: ci/tasks/brats.sh
