#!/bin/bash
set -e

UPSTREAM_CHECKOUT=$1
SUSE_CHECKOUT="master"

containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

rm upstream-manifest.yml || true
rm suse-manifest.yml ||true

wget "https://raw.githubusercontent.com/cloudfoundry/dotnet-core-buildpack/${UPSTREAM_CHECKOUT}/manifest.yml" --quiet -O upstream-manifest.yml
wget "https://raw.githubusercontent.com/SUSE/cf-dotnet-core-buildpack/${SUSE_CHECKOUT}/manifest.yml" --quiet -O suse-manifest.yml

built_versions=`ruby -ryaml -ruri <<EOF
manifest = YAML.load_file("suse-manifest.yml")
dependencies = manifest["dependencies"].select do |d|
  d["uri"].include?("dotnet-sdk")
end.each do |d|
  puts d["version"]
end
EOF
`
upstream_built_versions=`ruby -ryaml -ruri <<EOF
manifest = YAML.load_file("upstream-manifest.yml")
dependencies = manifest["dependencies"].select do |d|
  d["uri"].include?("dotnet-sdk")
end.each do |d|
  puts d["version"]
end
EOF
`

for v in ${upstream_built_versions}; 
do
    [[ $v =~ ^1\. ]] && continue;
   if ! containsElement $v ${built_versions};
   then
     echo "$v"
   fi
done
