---
<% versions = ["2.1.403", "2.1.503", "2.2.100"] %>

resources:
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/buildpacks-ci.git
    private_key: {{github-private-key}}
- name: depwatcher
  type: git
  source:
    uri: https://github.com/SUSE/cf-buildpacks-ci.git
    private_key: {{github-private-key}}
    paths: [dockerfiles/depwatcher]
    branch: incorporate_env_into_depwatcher
jobs:
<% versions.each do |version| %>
- name: build-dotnet-<%= version %>
  plan:
  - aggregate:
    - get: ci
    - get: depwatcher
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: registry.opensuse.org/cloud/platform/stack/rootfs/images/sle15
          username: {{docker-internal-username}}
          password: {{docker-internal-password}}
      inputs:
        - name: ci
        - name: depwatcher
      outputs:
        - name: artifacts
      params:
        DOTNET_VERSION: <%= version %>
        TERM: xterm
        STACK: sle15
        LOCAL_BUILD: "true"
        OAUTH_AUTHORIZATION_TOKEN: {{github-access-token}}
        AWS_ACCESS_KEY_ID: {{aws-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-key}}
        AWS_DEFAULT_REGION: us-east-1
        STAGING_BUILDPACKS_BUCKET: {{s3-staging-buildpacks-bucket}}
      run:
        path: ci/dotnet/tasks/build.sh
  - task: push-dotnet-cli-sources-to-obs
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: splatform/binary_builder_obs_opensuse
      inputs:
        - name: ci
      params:
        OBS_PROJECT: {{obs-buildpack-sources}}
        STAGING_BUILDPACKS_BUCKET: {{s3-staging-buildpacks-bucket}}
        OBS_USERNAME:  {{obs-username}}
        OBS_PASSWORD:  {{obs-password}}
        AWS_ACCESS_KEY_ID: {{aws-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-secret-key}}
        AWS_DEFAULT_REGION: us-east-1
        DOTNET_VERSION: <%= version %>
      run:
        path: ci/dotnet/tasks/push-obs-sources.sh
 <% end %>
