---
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: email.suse
  type: email
  source:
    smtp:
      anonymous: true
      host: {{notification-imap-alternate-host}}
      port: {{notification-imap-alternate-port}}
      ca_cert: |
        ((notification-ca-cert))
    from: {{notification-from}}
    to: [ {{notification-to}} ]
- name: ci
  type: git
  source:
    uri: git@github.com:SUSE/buildpacks-ci.git
    private_key: {{github-private-key}}
    branch: setup-release-process
- name: git.ruby-buildpack
  type: git
  source:
    uri: git@github.com:SUSE/cf-ruby-buildpack.git
    private_key: {{github-private-key}}
- name: git.ruby_buildpack-release
  type: git
  source:
    uri: git@github.com:SUSE/cf-ruby-buildpack-release.git
    private_key: {{github-private-key}}
- name: s3.suse-buildpacks-staging-ruby
  type: s3
  source:
    bucket: suse-buildpacks-staging
    regexp: ruby_buildpack-v([0-9-.]+)-.+\.zip
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
jobs:
- name: ruby-brats
  serial: true
  plan:
  - get: s3.suse-buildpacks-staging-ruby
    trigger: true
  - get: ci
  - get: git.ruby-buildpack
  - task: cleanup
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: ci
      params:
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
      run:
        path: ci/brats/tasks/cleanup.sh
  - task: brats
    input_mapping:
      git.buildpack: git.ruby-buildpack
      s3.suse-buildpacks-staging: s3.suse-buildpacks-staging-ruby
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: splatform/concourse-brats
      inputs:
        - name: git.buildpack
        - name: s3.suse-buildpacks-staging
        - name: ci
      outputs:
        - name: brats-ouput
        - name: mail-output
      params:
        GINKGO_NODES: 1
        PROXY_SCHEME: {{brats-proxy-scheme}}
        PROXY_PORT: {{brats-proxy-port}}
        PROXY_USERNAME: {{brats-proxy-username}}
        PROXY_PASSWORD: {{brats-proxy-password}}
        PROXY_HOST: {{brats-proxy-host}}
        CF_STACK: {{brats-cf-stack}}
        CF_ENDPOINT: {{brats-cf-endpoint}}
        CF_USERNAME: {{brats-cf-username}}
        CF_PASSWORD: {{brats-cf-password}}
        CF_ORG: {{brats-cf-org}}
        CF_SPACE: {{brats-cf-space}}
        PROJECT: {{obs-buildpacks-staging-project}}
      run:
        path: ci/brats/tasks/brats.sh
    on_failure: 
      put: email.suse
      params:
        subject: mail-output/subject-failed.txt
        body: mail-output/body-failed.txt
- name: ruby-release
  plan:
  - get: ci
  - get: git.ruby_buildpack-release
  - get: s3.suse-buildpacks-staging-ruby
    passed:
      - ruby-brats
    trigger: true
  - task: publish
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: splatform/binary_builder_obs_opensuse
      inputs:
        - name: ci
        - name: s3.suse-buildpacks-staging-ruby
        - name: git.ruby_buildpack-release
      outputs:
        - name: git-output
        - name: git-tag
        - name: mail-output
      params:
        GIT_MAIL: {{github-username}}
        GIT_USER: suse-cf-ci-bot
        PROJECT: {{obs-buildpacks-staging-project}}

      run:
        path: ci/brats/tasks/release_buildpack.sh
  - put: git.ruby_buildpack-release
    params:
      repository: git-output
      tag: git-tag/tag
  - put: email.suse
    params:
      subject: mail-output/subject.txt
      body: mail-output/body.txt
